### Site info:
title: Shuvomoy Das Gupta
tagline: Blog
author: Shuvomoy Das Gupta
email: shuvomoy [dot] dasgupta [at] gmail [dot] com
name: Blogs by Shuvomoy Das Gupta
description: "Blogs by Shuvomoy Das Gupta" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
url: https://shuvomoy.github.io/blog/
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
keywords: "Shuvomoy Das Gupta"
baseurl: "/blog" # the subpath of your site, e.g. /blog
locale: en_US

### Personal info and site tools info:
favicon:     "/images/favicon.ico"
aboutme: Hello world! I am <b>Shuvomoy Das Gupta</b>, a Ph.D. student at the <a href="https://orc.mit.edu/">MIT Operations Research Center</a>. This blog is an attempt to improve my English. Here is my <a href="https://shuvomoy.github.io/site/">academic website</a>.  


### Site setting:
ShowContactInfo: "False" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == False
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "

      
Blogroll:



    - name: My website

      href: https://shuvomoy.github.io/site/

      title: Shuvomoy's Website

    



### Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
paginate: 5
paginate: 5

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
    
